version: '2.4'

services:
  nginx:
    image: madsunshinecreations/webserver:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webserver/conf.d/:/etc/nginx/conf.d
      - /opt/madsunshinecreations/letsencrypt:/etc/letsencrypt
  print-simple:
    image: madsunshinecreations/print-simple:latest
    restart: unless-stopped
    volumes:
      - /opt/madsunshinecreations/print-simple/printer-list.yaml:/etc/print-simple/printer-list.yaml
      - /opt/madsunshinecreations/print-simple/gcode:/gcode
  print-simple-ui:
    image: madsunshinecreations/print-simple-ui:latest
  octoprint-basilisk:
    image: madsunshinecreations/octoprint-preconfig
    restart: unless-stopped
    devices:
     - /dev/ttyBasilisk:/dev/ttyBasilisk
    volumes:
     - basilisk:/octoprint
     - /opt/madsunshinecreations/octoprint:/startup_config
    environment:
     - CONFIG_FILE_NAME=basilisk_config.yaml
     - USERS_FILE_NAME=basilisk_users.yaml
  octoprint-draco:
    image: madsunshinecreations/octoprint-preconfig
    restart: unless-stopped
    devices:
     - /dev/ttyDraco:/dev/ttyDraco
    volumes:
     - draco:/octoprint
     - /opt/madsunshinecreations/octoprint:/startup_config
    environment:
     - CONFIG_FILE_NAME=draco_config.yaml
     - USERS_FILE_NAME=draco_users.yaml
  octoprint-igloo:
    image: madsunshinecreations/octoprint-preconfig
    restart: unless-stopped
    devices:
     - /dev/ttyIgloo:/dev/ttyIgloo
    volumes:
     - igloo:/octoprint
     - /opt/madsunshinecreations/octoprint:/startup_config
    environment:
     - CONFIG_FILE_NAME=igloo_config.yaml
     - USERS_FILE_NAME=igloo_users.yaml
  octoprint-tiger:
    image: madsunshinecreations/octoprint-preconfig
    restart: unless-stopped
    devices:
     - /dev/ttyTiger:/dev/ttyTiger
    volumes:
     - tiger:/octoprint
     - /opt/madsunshinecreations/octoprint:/startup_config
    environment:
     - CONFIG_FILE_NAME=tiger_config.yaml
     - USERS_FILE_NAME=tiger_users.yaml
  octoprint-godzilla:
    image: madsunshinecreations/octoprint-preconfig
    restart: unless-stopped
    devices:
     - /dev/ttyGodzilla:/dev/ttyGodzilla
    volumes:
     - godzilla:/octoprint
     - /opt/madsunshinecreations/octoprint:/startup_config
    environment:
     - CONFIG_FILE_NAME=godzilla_config.yaml
     - USERS_FILE_NAME=godzilla_users.yaml
  octoprint-shadow:
    image: madsunshinecreations/octoprint-preconfig
    restart: unless-stopped
    devices:
     - /dev/ttyShadow:/dev/ttyShadow
    volumes:
     - shadow:/octoprint
     - /opt/madsunshinecreations/octoprint:/startup_config
    environment:
     - CONFIG_FILE_NAME=shadow_config.yaml
     - USERS_FILE_NAME=shadow_users.yaml
volumes:
  draco:
  igloo:
  basilisk:
  godzilla:
  tiger:
  shadow:
